### ISSUE TITLE
Will the code be made available? 

### ISSUE THREAD

**Issue by dhudsmith** [BioMedIA-MBZUAI/EchoCoTr#1]
The paper/chapter (https://arxiv.org/pdf/2209.04242.pdf, https://link.springer.com/chapter/10.1007/978-3-031-16440-8_36) states that the code will be made available here. I would like to benchmark against this method. Any plans to post the code?

**Comment by rmuhtaseb** [comment]
Hi @dhudsmith. Code is pushed. Apologies for the delay.
